FROM  nvcr.io/nvidia/pytorch:23.06-py3

RUN apt-get update && apt-get install -y libsndfile1 ffmpeg
RUN pip install Cython
RUN pip install nemo_toolkit[all]

RUN pip install jupyterlab

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8890", "--allow-root" ]

