FROM python:3

WORKDIR /usr/src/app

COPY requirements-openai.txt ./
RUN pip install --no-cache-dir -r requirements-openai.txt
RUN pip install mlflow

CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8891", "--allow-root" ]