FROM  ghcr.io/mlflow/mlflow

WORKDIR /app

#FROM python:3

#WORKDIR /usr/src/app

#COPY requirements-openai.txt ./
#RUN pip install mlflow

# Set the MLflow server as the default command
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "8080"]